ToolbarWidgetWrapper: Fix crash when icon is not found
* attempt to fix crash when launching screenshot activity

FATAL EXCEPTION: main
Process: com.android.systemui:screenshot, PID: 13998
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.systemui/com.android.systemui.screenshot.scroll.LongScreenshotActivity}: android.content.res.Resources$NotFoundException: Drawable com.android.systemui:drawable/android15_patch_adaptive with resource ID #0x7f080607
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4048)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4235)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
 at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
 at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loopOnce(Looper.java:232)
 at android.os.Looper.loop(Looper.java:317)
 at android.app.ActivityThread.main(ActivityThread.java:8705)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
Caused by: android.content.res.Resources$NotFoundException: Drawable com.android.systemui:drawable/android15_patch_adaptive with resource ID #0x7f080607
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/android15_patch_adaptive.xml from drawable resource ID #0x7f080607
 at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:998)
 at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:766)
 at android.content.res.Resources.loadDrawable(Resources.java:1015)
 at android.content.res.Resources.getDrawableForDensity(Resources.java:1005)
 at android.content.res.Resources.getDrawable(Resources.java:944)
 at android.content.Context.getDrawable(Context.java:995)
 at com.android.internal.widget.ToolbarWidgetWrapper.setIcon(ToolbarWidgetWrapper.java:322)